#!/bin/bash

NAME=flower
DESC="flower daemon"

# Name of the projects settings module.
export DJANGO_SETTINGS_MODULE="niamoto.settings"

# Where the Django project is.
FLOWER_CHDIR="/home/niamoto/niamoto-portal"

# How to call "manage.py celery flower" (args...)
FLOWERCTL="/home/niamoto/flower_startup.sh"

set -e

case "$1" in
  start)
        echo -n "Starting $DESC: "
        start-stop-daemon --start --pidfile $PID_FILE \
            --chdir $FLOWER_CHDIR --chuid niamoto \
            --user niamoto --group niamoto --background \
            --make-pidfile \
            --exec "$FLOWERCTL"
        echo "$NAME."
        ;;

  stop)
        echo -n "Stopping $DESC: "
        PID=`ps -ef | awk '/[f]lower -A niamoto/{print $2}'`
        start-stop-daemon --stop --quiet --oknodo \
            --pid=$PID
        echo "$NAME."
        ;;
esac

exit 0
